### ISSUE TITLE
[superseded] normalizeExe

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/compilerdev#10]
@araq PR accepted for os.normalizeExe ?

it's a common gotcha

```nim
proc normalizeExe(file: string): string =
  # xxx common pattern, should be exposed in std/os, even if simple (error prone)
  when defined(posix):
    if file.len == 0: ""
    elif DirSep in file: file else: "./" & file
  else: file
```

=> so i can remove this also... $nim_prs_D/testament/testament.nim
```nim
            if defined(posix) and not exeFile.contains('/'):
              # "security" in Posix is actually just a euphemism
              # for "unproductive arbitrary shit"
              exeCmd = "./" & exeFile
            else:
              exeCmd = exeFile
```

**Comment by Araq** [comment]
ok.

**Comment by dom96** [comment]
Why is this an issue in the compilerdev repo? I'm not familiar with this repo but it doesn't sound like the right place to me. Am I missing something?

**Comment by Clyybber** [comment]
This proc doesn't have to be this complex actually. The `DirSep in file` is unneccessary, as `././SomeExecutable` is valid too.
EDIT: I see you made it an argument in `normalizePath`, then its fine and makes sense to cut redundant `./`s I guess

**Comment by Araq** [comment]
> Am I missing something?

No, you are not, it doesn't really belong into here.

**Comment by timotheecour** [comment]
well discussion moved to https://github.com/nim-lang/Nim/pull/14649 anyway
EDIT: was merged in https://github.com/nim-lang/Nim/pull/14668
