### ISSUE TITLE
Sigmatch hack 1: special case of 'nil' for distinct types

### ISSUE THREAD

**Issue by Araq** [nim-lang/compilerdev#2]
There is some code in sigmatch that allows ``nil`` for ``distinct pointer``. This either has to be documented and reflected in the spec or removed from the compiler (with the usual changelog entry and ``--useVersion:1.0`` protections):

```nim
  # currently line 1307

  of tyDistinct:
    a = a.skipTypes({tyOwned, tyGenericInst, tyRange})
    if a.kind == tyDistinct:
      if sameDistinctTypes(f, a): result = isEqual
      #elif f.base.kind == tyAnything: result = isGeneric  # issue 4435
      elif c.coerceDistincts: result = typeRel(c, f.base, a)
    elif a.kind == tyNil and f.base.kind in NilableTypes:
      result = f.allowsNil # XXX remove this typing rule, it is not in the spec
    elif c.coerceDistincts: result = typeRel(c, f.base, a)
```

**Comment by disruptek** [comment]
So the idea here is to make a match against a naked `nil` into an error, and insist that it is turned into a `MyPtr(nil)` instead?  That seems much better than matching on _any_ `nil`, to me.  I've seen some pretty gnarly nils out there.

Am I reading this right?

**Comment by Araq** [comment]
Yes, you do.
